# See : https://github.com/marketplace/actions/docker-metadata-action
name: Docker Metadata on Tags

# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch
on:
  workflow_dispatch:
    inputs:
      tag_input:
        description: 'Test scenario tag value'
        required: true
        type: string

jobs:
  docker-metadata:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        env:
          TAG_VALUE: v1.2
        with:
          images: ghusta/myapp
          tags: |
            type=semver,pattern={{version}}

      - name: Next
        run: |
          echo Input tag is ${{ inputs.tag_input }}
          echo Metadata tags = ${{ steps.meta.outputs.tags }}
          echo Metadata labels = ${{ steps.meta.outputs.labels }}
