# See : https://github.com/marketplace/actions/docker-metadata-action
name: Docker Metadata on Tags

# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch
on:
  push:
    tags:
      - '**'
    branches-ignore:
      - '**'

jobs:
  docker-metadata:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghusta/myapp
          tags: |
            # semver-compatible
            type=match,pattern=\d.\d.\d
            # not semver-compatible
            type=match,pattern=\d.\d

      - name: Next
        run: |
          echo Git ref is ${{ github.ref }}
          echo Git ref name is ${{ github.ref_name }}
          echo Metadata tags = ${{ join(fromJSON(steps.meta.outputs.json).tags, ', ') }}
          echo Metadata labels = ${{ join(fromJSON(steps.meta.outputs.json).labels, ', ') }}
