# See : https://github.com/marketplace/actions/docker-metadata-action
name: Docker Metadata on Tags using Suffix

# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch
on:
  push:
    tags:
      - '**'
    branches-ignore:
      - '**'

jobs:
  docker-metadata:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        env: 
          TAG_SUFFIX: '-test'
        with:
          images: ghusta/myapp
          sep-tags: ','
          sep-labels: ', '
          flavor: |
            latest=true
          tags: |
            # semver-only tags
            type=semver,pattern={{version}}
            type=semver,pattern={{version}},suffix=${{ env.TAG_SUFFIX }}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}.{{minor}},suffix=${{ env.TAG_SUFFIX }}

      - name: Docker meta no latest
        id: meta-no-latest
        uses: docker/metadata-action@v4
        env: 
          TAG_SUFFIX: '-fake'
        with:
          images: ghusta/myapp
          sep-tags: ','
          sep-labels: ', '
          flavor: |
            latest=false
            suffix=${{ env.TAG_SUFFIX }}
          tags: |
            # semver-only tags
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Next
        run: |
          echo Git ref is ${{ github.ref }}
          echo Git ref name is ${{ github.ref_name }}
          echo Metadata tags = ${{ steps.meta.outputs.tags }}
          echo Metadata labels = ${{ steps.meta.outputs.labels }}

      - name: Next with no latest
        run: |
          echo Git ref is ${{ github.ref }}
          echo Git ref name is ${{ github.ref_name }}
          echo Metadata tags = ${{ steps.meta-no-latest.outputs.tags }}
